name: deploy
on:
  push:
    branches:
      - release
  workflow_dispatch:
  

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install SSH Key
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.VPS_HOST }}
        
      - name: Deploy with rsync
        run: rsync -az * ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/fhtw/
        
      - name: Restart apache
        run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} /usr/sbin/apache2ctl restart
